### ISSUE TITLE
bug: Some rules flag based on Properties position on a resource

### ISSUE THREAD

**Issue by maafk** [cdklabs/cdk-nag#840]
### What is the problem?

To address the [NIST.800.53.R4-CloudWatchLogGroupRetentionPeriod](https://docs.aws.amazon.com/config/latest/developerguide/cw-loggroup-retention-period-check.html), I add an Aspect to set the [`RetentionInDays`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html#cfn-logs-loggroup-retentionindays) to 180.

When applied to a stack with some L2 constructs, the affected Cfn resource sets those properties in different orders, and as a result the resource is marked as non-compliant

### Reproduction Steps

```typescript
import * as cdk from 'aws-cdk-lib';
import { Stack, StackProps, Aspects, IAspect } from 'aws-cdk-lib';
import { NetworkLoadBalancedFargateService } from 'aws-cdk-lib/aws-ecs-patterns';
import { ContainerImage } from 'aws-cdk-lib/aws-ecs';
import { CfnLogGroup, LogGroup } from 'aws-cdk-lib/aws-logs';
import { Construct, IConstruct } from 'constructs';
import { NIST80053R4Checks } from 'cdk-nag';

class CdkNagTestStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);
    new NetworkLoadBalancedFargateService(this, 'MyNlbFargateService', {
      taskImageOptions: {
        image: ContainerImage.fromRegistry('amazon/amazon-ecs-sample'),
      }
    });
    new LogGroup(this, "MyLogGroup");
  }
}

class LogRetention implements IAspect {
  public visit(node: IConstruct): void {
    if (node instanceof CfnLogGroup) {
      node.addPropertyOverride('RetentionInDays', 180); //Ensure RetentionInDays is set
    }
  }
}

const app = new cdk.App();
new CdkNagTestStack(app, 'CdkNagTestStack');
Aspects.of(app).add(new LogRetention())
Aspects.of(app).add(new NIST80053R4Checks())
```
When doing a `cdk synth`, there are a number of nag rules violated, but `NIST.800.53.R4-CloudWatchLogGroupRetentionPeriod` is triggered on only one of the `AWS::Logs::LogGroup`s

I comment out `Aspects.of(app).add(new NIST80053R4Checks())`, and run a `cdk synth > tmp.yml`

The `NetworkLoadBalancedFargateService` creates a number of resources, including a `AWS::Logs::LogGroup`

```yaml
  MyNlbFargateServiceTaskDefwebLogGroup566BBF85:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: CdkNagTestStack/MyNlbFargateService/TaskDef/web/LogGroup/Resource
    Properties:
      RetentionInDays: 180
```

This resource throws the `NIST.800.53.R4-CloudWatchLogGroupRetentionPeriod`

However the `MyLogGroup` resource is synthed as:

```yaml
  MyLogGroup5C0DAD85:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 180
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: CdkNagTestStack/MyLogGroup/Resource
```

This resource _doesn't_ throw the `NIST.800.53.R4-CloudWatchLogGroupRetentionPeriod`

Only difference I notice is the `Properties` comes _before_ the [resource attributes](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-product-attribute-reference.html) when found as compliant, and _after_ the resource attributes when not compliant

### What did you expect to happen?

The Aspect to set Log group retention days would address the [NIST.800.53.R4-CloudWatchLogGroupRetentionPeriod](https://docs.aws.amazon.com/config/latest/developerguide/cw-loggroup-retention-period-check.html) rule regardless of where the Properties falls under the resource

### What actually happened?

[NIST.800.53.R4-CloudWatchLogGroupRetentionPeriod](https://docs.aws.amazon.com/config/latest/developerguide/cw-loggroup-retention-period-check.html) was hit on the following resource

```yaml
  MyNlbFargateServiceTaskDefwebLogGroup566BBF85:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: CdkNagTestStack/MyNlbFargateService/TaskDef/web/LogGroup/Resource
    Properties:
      RetentionInDays: 180
```

### cdk-nag version

2.13.1

### Language

Typescript
